// AUTOGENERATED FILE - DO NOT EDIT

var pt = window.PropTypes;
var pk = window['dash_calendar_timeline'];

pk.DashCalendarTimeline.propTypes = {items:pt.arrayOf(pt.shape({id:pt.oneOfType([pt.string,pt.number]),group:pt.oneOfType([pt.string,pt.number]),title:pt.string,start_time:pt.number,end_time:pt.number,canMove:pt.bool,canResize:pt.oneOfType([pt.oneOf(["left"]),pt.oneOf(["right"]),pt.oneOf(["both"])]),canChangeGroup:pt.bool,itemProps:pt.shape({className:pt.string,style:pt.objectOf(pt.any)}),hoverInfo:pt.string})),
 groups:pt.arrayOf(pt.shape({id:pt.oneOfType([pt.string,pt.number]),title:pt.string,rightTitle:pt.string,stackItems:pt.bool,height:pt.number})),
 default_time_start:pt.number,
 default_time_end:pt.number,
 drag_snap:pt.number,
 min_zoom:pt.number,
 max_zoom:pt.number,
 line_height:pt.number,
 item_height_ratio:pt.number,
 use_resize_handle:pt.bool,
 clickedItem:pt.shape({id:pt.oneOfType([pt.string,pt.number]),group:pt.oneOfType([pt.string,pt.number]),title:pt.string,start_time:pt.number,end_time:pt.number,canMove:pt.bool,canResize:pt.oneOfType([pt.oneOf(["left"]),pt.oneOf(["right"]),pt.oneOf(["both"])]),canChangeGroup:pt.bool,itemProps:pt.shape({className:pt.string,style:pt.objectOf(pt.any)}),hoverInfo:pt.string}),
 selectedItemInput:pt.objectOf(pt.any),
 id:pt.string,
 setProps:pt.any};
